add property, methods in author and blog
dimankan/dvog pull request #1
Opened 2022-05-28 05:12 UTC by dimankan

2022-05-28 05:14 UTC, dimankan commented on Dvog/Dvog.Domain/Author.cs
> +            Password = password;
test comment

2022-05-28 06:11 UTC, pingvin1308 requested changes

2022-05-28 06:11 UTC, pingvin1308 commented on Dvog/Dvog.Domain/Author.cs
> +        public string Login { get; }
Убрать свойства Login, Password, Email, Phone

2022-05-28 06:11 UTC, pingvin1308 commented on Dvog/Dvog.Domain/Author.cs
> +        public int Id { get; set; }
убрать set

2022-05-28 06:11 UTC, pingvin1308 commented on Dvog/Dvog.Domain/Author.cs
> +        public string FirstName { get; }
public string FirstName { get; }
public string SecondName { get; }
можно поменять на username

2022-05-28 06:11 UTC, pingvin1308 commented on Dvog/Dvog.Domain/Author.cs
> +            var blog = new Author(0, login, password, email, phone, firstName, secondName, birthday, DateTime.Now);
blog -> author

2022-05-28 06:11 UTC, pingvin1308 commented on Dvog/Dvog.Domain/Blog.cs
> +        CreatedDate = createdDate;
пока убери CreatedDate и UpdatedDate

2022-05-28 06:11 UTC, pingvin1308 commented on Dvog/Dvog.Domain/Blog.cs
> +    public Blog UpdateTitle(string newTitle)
Убрать методы UpdateTitle и UpdateText и Show

2022-06-11 05:23 UTC, pingvin1308 commented on Dvog/Dvog.API/Contracts/CreateBlogRequest.cs
> +    {
CreateBlogRequest(Title title, Text text) - попробовать добавить конструктор

2022-06-11 05:31 UTC, pingvin1308 commented on Dvog/Dvog.API/Controllers/BlogsController.cs
> +        public async Task<IActionResult> Update([FromRoute] int blogId)
UpdateBlogRequest

2022-06-11 05:33 UTC, pingvin1308 commented on Dvog/Dvog.API/Controllers/BlogsController.cs
> +                var blog = _blogs[idBlog];
Проверка наличие блога

2022-06-11 05:39 UTC, pingvin1308 commented on Dvog/Dvog.API/Controllers/BlogsController.cs
> +                var blog = _blogs[idBlog];
if (!_blogs.TryGetValue(idBlog, out var blog))
{
    return $"Блога c идентификатором {idBlog} не существует";
}

blog // используем полученный блог

2022-06-11 05:40 UTC, pingvin1308 commented on Dvog/Dvog.API/Controllers/BlogsController.cs
> +                var blog = _blogs[idBlog];
blogs[idBlog] = updatedBlog with { Id = blog.Id };

2022-06-11 05:42 UTC, pingvin1308 commented on Dvog/Dvog.API/Controllers/BlogsController.cs
> +            catch (Exception ex)
Обработку исключения можно убрать, так как тут не должно быть исключений. Все исключения мы будем обрабатывать в глобальном обработчике исключений

2022-06-11 07:14 UTC, pingvin1308 commented
Можешь вмержить

2022-06-11 07:16 UTC, merged